Azure-Samples/cosmosdb-chatgpt

- Services/ChatService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Summarize and rename chat session on first prompt

- CosmosDB-ChatGPT.csproj
- CosmosDB-ChatGPT.sln
- Pages/ChatPane.razor
- Pages/Error.cshtml
- Pages/Error.cshtml.cs
- Pages/Index.razor
- Pages/NavMenu.razor
- Pages/_Host.cshtml
- Pages/_Layout.cshtml
- Program.cs
- Properties/launchSettings.json
- README.md
- Services/Chat.cs
- Services/ChatService.cs
- Services/CosmosService.cs
- Services/OpenAiService.cs
- _Imports.razor
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> finalizing

- Pages/NavMenu.razor
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updating Variable Names

- Pages/ChatPane.razor
- Pages/Index.razor
- Pages/NavMenu.razor
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Updates for multiuser session and mobile UI

- Pages/NavMenu.razor
- Services/ChatService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
>  Delete session not updating current session in remote  sessions

- README.md
- azuredeploy.bicep
- azuredeploy.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Deployment updates

- Pages/ChatPane.razor
- Pages/NavMenu.razor
- Services/ChatService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Consistent naming for async methods

- Services/ChatService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix for error on deleting all chats

- CosmosDB-ChatGPT.csproj
- Pages/NavMenu.razor
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> fix click event for left nav

- .devcontainer/devcontainer.json
> Update devcontainer spec

- Services/OpenAiService.cs
To meet .NET code sample style standards.
> Rename system prompt text

- Pages/ChatPane.razor
> Implement token label

- .devcontainer/devcontainer.json
> Update devcontainer.json with Bicep extension

- Models/Session.cs
- Options/OpenAi.cs
- Pages/ChatPane.razor
- Program.cs
- Services/ChatService.cs
- Services/CosmosDbService.cs
- Services/OpenAiService.cs
- appsettings.json
Modify session to include tokens used
Add session to batch upsert
* ...
```
[X] Yes
[ ] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Use tokens for conversation memory

- Pages/NavMenu.razor
- Services/ChatService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fixed conversation builder, added tokens used to session label

- Pages/ChatPane.razor
- Pages/Index.razor
Update NavMenu for Token utilized after every prompt.
No
``
> Update NavMenu for Token utilized after every prompt.

- Services/ChatService.cs
- Services/OpenAiService.cs
- azuredeploy.bicep
- azuredeploy.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Migrate back to gpt-turbo-35

- Pages/ChatPane.razor
- Services/OpenAiService.cs
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> render line breaks in prompts and completions.

- Pages/ChatPane.razor
Hide's the chat box at the bottom of the screen if no chat is currently selected.
> Hide textbox if no chat is selected

- Options/OpenAi.cs
- Program.cs
- Services/OpenAiService.cs
- appsettings.json
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> change deploymentName to modelName

- Pages/ChatPane.razor
Improved the formatting of code blocks.
Markdown code blocks are now converted to html code tags which renders better. 
```
<pre>
<code>
@if(markdown)
{
var text = ConvertToHtml(text);
}
</code>
</pre> 
```
Multiple code blocks per response are also supported.
This paves the way for syntax highlighters such as "highlight.js" to also be added.
```
[ ] Yes
[ x ] No
```
```
[ ] Bugfix
[ x ] Feature
[ x ] Code style update (formatting, local variables)
```
> Add conversion of markdown code blocks to html code block

- Program.cs
- Services/ChatService.cs
- Services/OpenAiService.cs
MaxConversationTokens is specified in OpenAiService but not used in that service. I moved this dependency to the parent ChatService.
> Moved maxconversationtokens to ChatService

- azuredeploy.bicep
- azuredeploy.json
Old template still said `OPENAI__DEPLOYMENT`
> Update ARM templates with `OPENAI__MODELNAME`

- Services/CosmosDbService.cs
This method order makes more sense in a reading order and exactly map with both the Learn and Skillable lab instructions.
> Reorder methods in Cosmos DB service

- azuredeploy-no-aoai.bicep
- azuredeploy-no-aoai.json
- cosmoschatgpt.csproj
- readme.md
- Added a new bicep and ARM template to allow users to deploy the solution using an existing Azure OpenAI account.
- Added additional regions in both templates to reflect additional regions where Azure OpenAI is deployed.
- Updated README.MD with instructions on new deployment option as well as clarified installation instructions when deploying from this repo vs forked repos.
- Updated Azure OpenAI client package.
- Updated Cosmos DB package.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
[X] Documentation content changes
```
> Add deployment option for existing OpenAI accounts

- readme.md
* Typo "Azure Open AI service"→"Azure OpenAI Service"
https://github.com/Azure-Samples/cosmosdb-chatgpt/blob/main/readme.md 
#PingMSFTDocs
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Typo "Azure Open AI service"→"Azure OpenAI Service"

- .devcontainer/devcontainer.json
- .github/workflows/validate.yml
- Services/ChatService.cs
- Services/OpenAiService.cs
- cosmoschatgpt.csproj
> Push to .NET 8

- Services/ChatService.cs
- Services/OpenAiService.cs
- cosmoschatgpt.csproj
- readme.md
> Update `start` branch

- src/Services/SemanticKernelService.cs
Adds missing using statements
```
[ ] Yes
[x ] No
```
```
[x] Bugfix
[ ] Feature
```
> Added missing using statements for lab exercise

- README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> add azd cli
